
# ???? ???????
server.port=8080

# ???????? ??????????
spring.application.name=LubimyCzytac-dev

# ========== ???? ?????? MySQL (?????????) ==========
spring.datasource.url=jdbc:mysql://localhost:3306/lubimyczytac
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate ?????????
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# ========== ?????? ==========
server.servlet.session.timeout=7d
server.servlet.session.cookie.max-age=2592000
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=false
server.servlet.session.cookie.name=LUBIMY_SESSION_DEV

